scrape_configs:
  - job_name: 'dockerswarm'
    scrape_interval: 5s
    # Read the Docker Swarm api to discover the services and containers
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # Keep only the tasks that are running
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      # Keep only the tasks that have the label prometheus-port
      - source_labels: [__meta_dockerswarm_service_label_prometheus_port]
        regex: .+
        action: keep
      # Rename the job to the service name (but remove the stack name)
      - source_labels: [__meta_dockerswarm_service_name]
        regex: .*_(.+)
        replacement: $1
        target_label: job
      # Set the ip and port where the /metrics are exposed
      - source_labels: [__address__, __meta_dockerswarm_service_label_prometheus_port]
        regex: ([^:]+):\d+;(\d+)
        replacement: $1:$2
        target_label: __address__
