tts-1       | ++ python3 -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))'
tts-1       | + export LD_LIBRARY_PATH=/root/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib
tts-1       | + LD_LIBRARY_PATH=/root/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib
tts-1       | + uvx --from 'huggingface_hub[cli]' huggingface-cli login --token
tts-1       | usage: huggingface-cli <command> [<args>] login [-h] [--token TOKEN]
tts-1       |                                                 [--add-to-git-credential]
tts-1       | huggingface-cli <command> [<args>] login: error: argument --token: expected one argument
tts-1 exited with code 2
stt-1       | usage: huggingface-cli <command> [<args>] login [-h] [--token TOKEN]
stt-1       |                                                 [--add-to-git-credential]
stt-1       | huggingface-cli <command> [<args>] login: error: argument --token: expected one argument
stt-1 exited with code 2