"""Add name and plan fields to User

Revision ID: 32ba45e0d9a1
Revises: 
Create Date: 2025-07-09 10:38:00.109493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ba45e0d9a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=False, server_default='free'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plan')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
